import React from 'react';

export default React.createContext({
  userData: {},
  files: [],
  progress: 0,
  isLoadingRef: false,
  filesEx: [],
  progressEx: 0,
  isLoadingRefEx: false,
  processBotton: false,
  processBottonEx: false,
  isSuccess: false,
  isError: false,
  isSuccessEx: false,
  isErrorEx: false,
  removeUser: () => {},
  updateUserData: (newUserData) => {},
  updateFiles: (newFiles) => [],
  updateProgress: (newProgress) => 0,
  toggleLoading: () => false,
  updateFilesEx: (newFilesEx) => [],
  updateProgressEx: (newProgressEx) => 0,
  toggleLoadingEx: () => false,
  toggleError: () => false,
  toggleErrorEx: () => false,
  toggleSuccess:() => false,
  toggleSuccessEx: () => false,
  toggleProcessBotton: () => false,
  toggleProcessBottonEx: () => false,
});